######################################################################
# Automatically generated by qmake (3.0) ?? ????. 4 09:30:12 2013
######################################################################

TEMPLATE = app
TARGET = gu
INCLUDEPATH += .

# Input
HEADERS += appl.h
SOURCES += appl.cpp main.cpp
